### ISSUE TITLE
Cannot read history of undefined in componentDidUnload

### ISSUE THREAD

**Issue by matteobortolazzo** [wanoo21/stencil-route-listener#2]
Hi, the component works but it gives this error at startup:

![errorr](https://user-images.githubusercontent.com/15217470/48661982-0c1e7600-ea7b-11e8-97ba-460302741ed0.PNG)

What can it be?

**Comment by wanoo21** [comment]
Hi, did you send 'props' property to 'ip-stencil-route-listener' component? 
It seems to be undefined!

**Comment by matteobortolazzo** [comment]
Yes, I copied your example here https://github.com/wanoo21/stencil-route-listener/blob/master/src/components/app-root.tsx

**Comment by wanoo21** [comment]
What version of @stencil/router do you have?

**Comment by matteobortolazzo** [comment]
@wanoo21 0.3.1

**Comment by wanoo21** [comment]
I can't reproduce it on my side, are there any chances that you somehow change `props`?
Just pushed some fixes, let me know how it works on your side!

**Comment by matteobortolazzo** [comment]
Can you push it on NPM?

**Comment by wanoo21** [comment]
Pushed

**Comment by matteobortolazzo** [comment]
Sorry, seems to be random. Here's [the repo](https://github.com/matteobortolazzo/pomice) and here's the [test web site](https://thinkasync.azurewebsites.net/). Maybe you can see what's wrong.
